package com.toiser.myapp

import com.toiser.myapp.MetroStationEnum.*

// Metro stations
val stationNamesDepartureA = arrayListOf(
    DEPART,
    BASSO,
    BELLEFONTAINE,
    REYNERIE,
    MIRAIL,
    BAGATELLE,
    MERMOZ,
    FONTAINE_LESTANG,
    ARENES,
    PATTE_OIE,
    SAINT_CYP,
    ESQUIROL,
    CAPITOLE,
    JJA,
    MARENGO,
    JOLIMONT,
    ROSERAIE,
    ARGOULETS,
    BALMA)

val stationNamesDepartureB = arrayListOf(
    DEPART,
    RAMONVILLE,
    UPS,
    PHARMA,
    RANGUEIL,
    SAOUZELONG,
    SAINT_AGNE,
    EMPALOT,
    SAINT_MICHEL,
    PALAIS_JUSTICE,
    CARMES,
    VERDIER,
    JJB,
    JEANNE_DARC,
    COMPANS,
    CANAL_MIDI,
    MINIMES,
    BARRIERE_PARIS,
    VACHE,
    TROIS_COCUS,
    BORDEROUGE)

val stationNamesArrivalA = arrayListOf(
    ARRIVEE,
    BASSO,
    BELLEFONTAINE,
    REYNERIE,
    MIRAIL,
    BAGATELLE,
    MERMOZ,
    FONTAINE_LESTANG,
    ARENES,
    PATTE_OIE,
    SAINT_CYP,
    ESQUIROL,
    CAPITOLE,
    JJA,
    MARENGO,
    JOLIMONT,
    ROSERAIE,
    ARGOULETS,
    BALMA)

val stationNamesArrivalB = arrayListOf(
    ARRIVEE,
    RAMONVILLE,
    UPS,
    PHARMA,
    RANGUEIL,
    SAOUZELONG,
    SAINT_AGNE,
    EMPALOT,
    SAINT_MICHEL,
    PALAIS_JUSTICE,
    CARMES,
    VERDIER,
    JJB,
    JEANNE_DARC,
    COMPANS,
    CANAL_MIDI,
    MINIMES,
    BARRIERE_PARIS,
    VACHE,
    TROIS_COCUS,
    BORDEROUGE)